# Generated by Django 4.0.4 on 2022-05-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(choices=[('Toronto', 'Toronto'), ('Vancouver', 'Vancouver'), ('Ottawa', 'Ottawa'), ('Calgary', 'Calgary'), ('Montreal', 'Montreal')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Vehicle', 'Vehicle'), ("Women's Clothing & Shoes", "Women's Clothing & Shoes"), ("Men's Clothing & Shoes", "Men's Clothing & Shoes"), ('Furniture', 'Furniture'), ('Electronics', 'Electronics')], max_length=200, null=True)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_app.warehouse')),
            ],
        ),
    ]
